version: "3.9"
services:
  web:
    build: .
    image: "hitcount:latest"
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: True
    container_name: "hitcount"
  redis:
    image: "redis:alpine"
